version: '3.8'

networks:
  node-microservices:
    name: node-microservices

services:
  mongo:
    image: mongo:6.0
    ports:
      - '8001:27017'
    networks:
      - node-microservices

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: defaultDB
    ports:
      - '8002:5432'
    networks:
      - node-microservices

  auth-service:
    build:
      context: ./services/auth-service
    volumes:
      - /home/node/app/node_modules/
      - ../scoop-user-frontend:/home/node/app/
    command: ['npm', 'run', 'start']
    env_file: ./services/auth-service/.env
    ports:
      - '8003:8003'
    networks:
      - node-microservices
